services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "CheengizsBlogDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "OUV1wvuo1S&^71"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
